### ISSUE TITLE
Incorrect firmware version displayed 

### ISSUE THREAD

**Issue by Hackinside** [fixelsan/3do-ode-firmware#10]
**3DO model:** FZ-1-E
**ODE HW:** FZ-1 ODE
#
At first, it displays V.1.0.0. Loading a game and returning to the ODE menu via the open/close button, the system returns with a different version such as V 1.0.2, V 1.0.3, V 1.0.5 and so on. 
# 
[Video](https://youtu.be/kmMmU2e2tV0)

**Comment by trapexit** [comment]
That is intentional. It's counting the number of button presses effectively. Why? That is for users to find out.

**Comment by Hackinside** [comment]
LOL I got it now.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Hackinside** [comment]
![20220930_004700](https://user-images.githubusercontent.com/37005360/193161969-6b998e84-b7a2-424d-b2c2-4fcc08aa8a8a.jpg)
LOL I got it 👌
