### ISSUE TITLE
Issues with FZ-EM256 Memory Unit?

### ISSUE THREAD

**Issue by the0remora** [fixelsan/3do-ode-firmware#14]
I am using the **Internal** ODE with the FZ-EM256 Memory Unit. When I try to boot my Japanese FZ-1 with it plugged in boots into the Fixel Launcher (background and white borders) but displays no text.

I am booting from an exfat formated SSD.

I have not tried cleaning the Expansion port or connector yet. They look to be in good shape. 

At the suggestion of Ray01 on the 3DO Discord I tested with an SD card and the SSD disconnected with the same result.

Below are pictures showing the 3DO booted up both with the Memory Unit connected and disconnected.
![Working](https://user-images.githubusercontent.com/11638101/223571194-e791c5bf-3e79-4d65-8f59-f4949a6e060d.jpg)
![NotWorking](https://user-images.githubusercontent.com/11638101/223571370-413f1ad8-2709-4ce0-bebb-cd3695421802.jpg)

**Comment by fixelsan** [comment]
Issue is known and is fixed in the next menu release.
