### ISSUE TITLE
ODE crashes whenever advancing beyond the first "page" of directories

### ISSUE THREAD

**Issue by vrai** [fixelsan/3do-ode-firmware#15]
I'm using version 0.57 (the one installed by default) on an FZ-10 and am getting consistent crashes whenever I try to advance beyond the first page of any directory listing.

Selecting subdirectories or cue/iso files from the first page of any directory works fine. But trying to scroll beyond the bottom of the screen, or using the page advance button results in the music hanging, then a system restart.

I've uploaded a video of the problem in action here: https://drive.google.com/file/d/18BbMKKfEQVesLvioKLCNtmaaCfAPNSvs/view?usp=share_link

**Comment by fixelsan** [comment]
it looks like corrupted fat. i'm unable to recreate the issue, please create an image of your drive and share it.

**Comment by vrai** [comment]
Is there an upper limit on SD card size that's supported?

**Comment by vrai** [comment]
I switched from a 512GB card to a 256GB one, and am still seeing the same issues. I've noticed that the SD Card Formatter tool is creating ExFAT partitions. I'll try again with a FAT32 partition on the 256GB card.

**Comment by vrai** [comment]
Switching to FAT32 (rather than ExFAT) solved the problem
