### ISSUE TITLE
Game crash: Oyaji Hunter Mahjong

### ISSUE THREAD

**Issue by SnowyAria** [fixelsan/3do-ode-firmware#16]
Ran into a bit of a doozy. The short version is that it crashes upon loading the last stage of the game (and a few harder to reproduce locations). On emulator, it fails to load a certain image correctly, but still proceeds with the game after. The original disc on console works as expected.

To reproduce:

- On the title screen, do not press start. Enter Up, Right, Down, Left, Up, Down, Left, Right, L, R, B, C, B to reach the level select.
- Scroll down to Stage 5 and press A.
- After the loading screen with the star ratings on the right side (see below screenshot), the ODE crashes and resets. On Phoenix, the next image fails to load, but results in NOW LOADING appearing a second time over the previous image.

How the crash looks on Phoenix with the extra loading:
![image](https://user-images.githubusercontent.com/35874861/228726860-73c018d1-990a-4bd7-a4d8-14f85f4056c3.png)

Here's the in-game image telling you the level select code in case it's easier to see that way:
![image](https://user-images.githubusercontent.com/35874861/228728711-c97a3620-7d30-4644-8694-05a8b1139ddf.png)

Feel free to reach out to me if you have any questions either here or over in the 3DO discord. Thanks!

**Comment by DerekPascarella** [comment]
Was able to replicate this on FZ-1 internal ODE, and funnily enough, also on MNEMO's ODE on latest firmware (v2021-11-04).

**Comment by fixelsan** [comment]
i was able to replicate this on FZ-1 (NA) with CD-R... Not sure what we're looking for here.

**Comment by Arjak89** [comment]
I have also had random crashes occur while playing this game. I'm using the XPort on an American FZ-10.
