### ISSUE TITLE
USB device compatibility issues

### ISSUE THREAD

**Issue by trapexit** [fixelsan/3do-ode-firmware#2]
Device : ADATA 32GB
VID/PID: 125F:DB8A
Issue: Doesn't mount
https://www.amazon.com/ADATA-UV128-Retractable-Capless-AUV128-32G-RBE/dp/B00B7JLZQQ/

Device: Unknown
VID/PID: 058F:6387
Issue: Doesn't mount

Device: generic TF2USB adapter 
VID/PID: 1908:0226
Issue: Doesn't mount

**Comment by fixelsan** [comment]
fixed in 0.20

**Comment by Hackinside** [comment]
**3DO model:** FZ-1-E
**ODE HW:** FZ-1 ODE
#
**Brand** JSL JDTDC
**Capacity:** 256GB 
**Vendor ID:**  `0x2537` (Norel Systems Ltd.)
**Product ID:** `0x1083`
**Sold on** [Amazon](https://www.amazon.co.uk/dp/B0BDQGWXRG)
**Issue:** unable to return to ODE Menu sometimes
#

**Brand:** Elctman
**Capacity:** 64GB
**Vendor ID:** `0x090C` (Silicon Motion, Inc. - Taiwan)
**Product ID:** `0x1000`
**Sold on** [Amazon](https://www.amazon.co.uk/dp/B0BBL8KMG2)
**Issue:** Most of the games hang/crash at some point, unable to return to the ODE menu or blank screen
#

[Video](https://youtu.be/Cn_2oq-dUfo)
