### ISSUE TITLE
Suggestion - Not issue - Installation location

### ISSUE THREAD

**Issue by calaerial** [fixelsan/3do-ode-firmware#7]
Hello, 

I have been playing with my new ODE for a week now and have come to the view that (Unless Fixel has some suggestion as to why this shouldnt be done) the suggested installation location for the ODE may not be the easiest/best one if looking for a stock appearance. 

The suggested location is perfectly suitable, but requires the loss of the entire CD assembly and of course the front facia, necessitating either gluing it to the front of the chassis or using a 3D printed replacement. 

I have found that a more stock appearance can be obtained by leaving the entire CD assembly as it is, feeding the ribbon cables up the back and simply placing the ODE on top of the back of the CD tray.  This also means you dont need to find a place to store the CD assembly if you wish to keep it, it just stays where it is. 

There is sufficient height available that the only item which needs to be removed is the RF shielding. A small hole could be cut in that to allow the USB port to pop through if needed. 

Just a suggestion. May be that others have also gone this route, perhaps might be worth adding to the installation instructions as an option.

**Comment by fixelsan** [comment]
can you provide some pictures?

**Comment by calaerial** [comment]
Hello Felix,

Of course, i'm away this evening but should be able to open up the 3DO
tomorrow afternoon and send through some pictures.

It may be that there are reasons why this method are less than optimal for
some, but it certainly seems to be working for me :)

Kind regards,

Mark

**Comment by calaerial** [comment]
Photos attached

Kind regards,

Mark

 20221127_104847.jpg
<https://drive.google.com/file/d/11aP2iywlUuAdpHtLlYutSh2GoqlUvlw_/view?usp=drive_web>

 20221127_104906.jpg
<https://drive.google.com/file/d/11PB6ndMIpdWvH_amLFJFSZDSKGvqeElU/view?usp=drive_web>

 20221127_104917.jpg
<https://drive.google.com/file/d/11HxFhbtK9E8BiUv6vRWZLsWBMpBKB7hX/view?usp=drive_web>
