### ISSUE TITLE
NTSC/PAL Vertical position issue

### ISSUE THREAD

**Issue by Hackinside** [fixelsan/3do-ode-firmware#9]
3DO model: FZ-1-E
The issue is shown in the following [video](https://youtu.be/okuzBPH4270).
[![IMAGE ALT TEXT](https://i9.ytimg.com/vi/ZXmoo3P4iCk/mq2.jpg?sqp=CNCqvpkG&rs=AOn4CLAZmKysCCblbs0FHfMrbB-dqLCg8g)](https://www.youtube.com/watch?v=okuzBPH4270 "Test ODE 1")

**Comment by fixelsan** [comment]
confirmed

**Comment by Hackinside** [comment]
It is happening to my Japanese FZ-1 too. 
## Normal Mode
![Normal Mode](https://user-images.githubusercontent.com/37005360/193162665-afb86e39-6449-4db6-8985-4757151b8b11.jpg)
## Under Scan activated
![Underscan Uode](https://user-images.githubusercontent.com/37005360/193162701-40627ec4-89e1-486a-851f-7e6e432b810f.jpg)

**Comment by fixelsan** [comment]
overscan positioning is fixed in the next menu release
